---
title: "colon"
output: html_document
date: "2023-04-30"
---

```{r setup, include=FALSE}
#install.packages("BiocManager")
```
filter rows with phosphorylation:
```{r}
filepath <- "C:\\Users\\Beatrice\\Downloads\\colon_cancer_combined_modified_peptide.tsv"
input <- read.table(filepath, header=TRUE, sep="\t", quote="", comment.char="")
filtered_input <- input[grepl("79.9663", input$"Assigned.Modifications"), ]
#colnames(input)
#nrow(input)
#nrow(filtered_input)
#filtered_input
```

```{r}
# Filter the column names for stage I_II proteins
stage_I_II_columns <- grep("^I_II_[0-9]+\\.Spectral.Count", colnames(filtered_input), value = TRUE)
#print(stage_I_II_columns)

# Extract the protein IDs with non-zero counts in stage I_II
stage_I_II_protein_ids <- filtered_input$Protein.ID[rowSums(filtered_input[stage_I_II_columns] != 0) > 0]

# Remove duplicates and display the list of protein IDs detected in stage I_II
stage_I_II_protein_ids <- unique(stage_I_II_protein_ids)
print(stage_I_II_protein_ids)
```
```{r}
# Filter the column names for stage III_IV proteins
stage_III_IV_columns <- grep("^III_IV_[0-9]+\\.Spectral.Count", colnames(filtered_input), value = TRUE)
#print(stage_III_IV_columns)

# Extract the protein IDs with non-zero counts in stage III_IV
stage_III_IV_protein_ids <- filtered_input$Protein.ID[rowSums(filtered_input[stage_III_IV_columns] != 0) > 0]

# Remove duplicates and display the list of protein IDs detected in stage III_IV
stage_III_IV_protein_ids <- unique(stage_III_IV_protein_ids)
print(stage_III_IV_protein_ids)
```

```{r}
# Install the required packages
#install.packages("venneuler")
#install.packages("VennDiagram")
install.packages("futile.logger")
```
```{r}

# Load the required package
library(VennDiagram)

list1 <- stage_III_IV_protein_ids
list2 <- stage_I_II_protein_ids

venn.diagram(list("stage III_IV"=list1, "stage I_II"=list2),
             fill = c("cyan","red"),
             cex= 1.5,
             filename = "colon cancer VennDiagram.png",
             print.mode =c("raw", "percent"))


```
```{r}
library(VennDiagram)

# your data
#foo <- c('a','b','c','d')
#baa <- c('a','e','f','g')
list1 <- stage_III_IV_protein_ids
list2 <- stage_I_II_protein_ids

# Generate plot
v <- venn.diagram(list(list1=list1, list2=list2),
                  fill = c("orange", "blue"),
                  alpha = c(0.5, 0.5), cat.cex = 0.5, cex=0.5,
                  width = 20,  # Adjust width of the diagram
                  height = 22,  # Adjust height of the diagram
                  filename=NULL)

# have a look at the default plot
grid.newpage()
grid.draw(v)

# have a look at the names in the plot object v
lapply(v,  names)
# We are interested in the labels
lapply(v, function(i) i$label)

# Over-write labels (5 to 7 chosen by manual check of labels)
# in foo only
v[[5]]$label  <- paste(setdiff(list1, list2), collapse="\n")  
# in baa only
v[[6]]$label <- paste(setdiff(list2, list1)  , collapse="\n")  
# intesection
v[[7]]$label <- paste(intersect(list1, list2), collapse="\n")  

# plot  
grid.newpage()
grid.draw(v)
```

```{r}
common_ids <- intersect(stage_III_IV_protein_ids, stage_I_II_protein_ids)

# Determine the size of the larger list
table_size <- max(length(stage_III_IV_protein_ids), length(stage_I_II_protein_ids))

# Extend the smaller list with empty values to match the size of the larger list
extend_list <- function(list, size) {
  if (length(list) < size) {
    list <- c(list, rep(NA, size - length(list)))
  }
  return(list)
}

stage_III_IV_protein_ids_extended <- extend_list(stage_III_IV_protein_ids, table_size)
stage_I_II_protein_ids_extended <- extend_list(stage_I_II_protein_ids, table_size)

df <- data.frame(stage_III_IV_protein_ids = stage_III_IV_protein_ids_extended,
                 stage_I_II_protein_ids = stage_I_II_protein_ids_extended,
                 common_ids = ifelse(stage_III_IV_protein_ids_extended %in% common_ids, stage_III_IV_protein_ids_extended, NA))

df


# Load the 'openxlsx' package
library(openxlsx)

# Export the table to Excel
write.xlsx(df, "protein_ids_table.xlsx", row.names = FALSE)

```

