---
title: "colon_cancer_comb_protein"
output: html_document
date: "2023-06-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load the 'openxlsx' package
library(openxlsx)

# Read the XLSX file into R
data <- read.xlsx("C:\\Users\\Beatrice\\Documents\\Project\\colon_cancer_combined_protein.xlsx")

# View the data
#print(data)
colnames(data)

```

```{r}
# Extract the "Protein" column from the data
protein_column <- data$Protein

# Write the protein column to a text file
writeLines(protein_column, "protein_list.txt")
```


```{r}
library(readxl)
library(writexl)

# Load the Excel file
df <- read_excel("C:\\Users\\Beatrice\\Documents\\Project\\colon_cancer_combined_protein.xlsx")

# Filter proteins with more than 1 peptide
df_filtered <- subset(df, df$`Combined Total Peptides` > 1)

# Get the MaxLFQ intensity columns
maxlfq_columns <- grep(".MaxLFQ.Intensity$", colnames(df), value = TRUE)

# Calculate the percentage of samples with values for each protein
sample_count <- ncol(df) - length(maxlfq_columns)
df_filtered$SamplePercentage <- rowSums(!is.na(df_filtered[maxlfq_columns])) / sample_count

# Filter proteins with values in more than 50% of the samples
df_filtered <- subset(df_filtered, SamplePercentage > 0.5)

# Select the desired columns for the final filtered data

filtered_columns <- c(`Protein`, `Protein ID`, `Entry Name`, `Gene`, maxlfq_columns)
df_filtered <- df_filtered[filtered_columns]

# Save the filtered data to a new Excel file
write_xlsx(df_filtered, "filtered_proteins.xlsx")

```

